### PR TITLE
Kinematics fix

### LINKED ISSUE #39: Kinematics.py should be in the examples folder
The only .py files which should be in the root are ones that need to be there as a necessity of the build system.

### LINKED ISSUE #40: Kinematics.py is undocumented.
At the moment there's no documentation in kinematics.py or in the wider documentation about what this script does.

### LINKED ISSUE #41: Kinematics.py is untested
Other scripts in the examples/ directory are at least run via doctests. To guard against regressions, kinematics.py should be similarly tested.

### PR DESCRIPTION
**Pull request by jb803**
I've then moved the core of the kinematics code into a new firefish.kinematics module and created a KinematicBody and KinematicSimulation class and then reimplemented it using the new classes as kinematics_example.py

For some reason that I don't understand the docs test of Travis fails. This doesn't happen on my machine and I can run: sphinx-build -b html doc/ build/html/ with no problems so I'm lost as to the cause.

This should fix #41 #40 and #39 

Fixes #41. Fixes #40. Fixes #39.

### CODE REVIEW

**Comment by rjw57** [comment]
> This doesn't happen on my machine and I can run: sphinx-build -b html doc/ build/html/ with no problems so I'm lost as to the cause.

What about running via tox?

**Comment by jb803** [comment]
It was working fine on tox till I reinstalled everything whilst trying to fix a problem I had with Python 3.

I assume it's because the version of sphinx we're using has changed? The error appears to be: 

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.

**Comment by rjw57** [comment]
> sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.

And so, does adding [sphinx-rtd-theme](https://pypi.python.org/pypi/sphinx_rtd_theme) to ``doc/requirements.txt`` help?

**Comment by rjw57** [comment]
> And so, does adding sphinx_rtd_theme to doc/requirements.txt help?

Since, FWIW, it appears to fix the docs testenv for me. (Remember to re-build the env with the ``-r`` flag to tox.)

**Comment by jb803** [comment]
Ah - I hadn't thought about the doc/requirements.txt folder. Just rerunning tox now. Will commit again if it all passes.

Cheers for this :)

**Comment by jb803** [comment]
Yep - updating requirements.txt and running tox -r  fixed it all on my machine. Committed the new version.

**Comment by rjw57** [comment]
:+1: for merging if it passes then

**Comment by rjw57** [comment]
I updated the PR original comment so that the referenced issues will be auto-closed when this is merged.

**Pull request merged**
