### PR TITLE
Adding Kinematics Python Program

### PR DESCRIPTION
**Pull request by lwc24**
Kinematics program written in python (by lwc24).

### CODE REVIEW

**Comment by jb803** [comment]
If you do 'git pull upstream master' and then do another commit and push then that might trigger it to do the checks?

**Comment by rjw57** [comment]
Yeah, looks like this branch drifted out of sync with master.

**Comment by jb803** [comment]
:+1:

**Comment by rjw57** [comment]
So this looks good to me with the following comments.

1. Why is "Kinematics.py" in the root of the repo? I'd have expected it to be under ``examples`` like similar scripts.
2. Python scripts conventionally don't use capitalisation in filenames.
3. There should be a docstring at the beginning of the program describing it. (See other examples.)
4. Ideally the docstring should include a doctest to run the program.

I'd ideally not have merged this. I'll open a PR which addresses the more serious issues.

**Comment by rjw57** [comment]
So, it would've been a :-1: from me as is.

**Comment by rjw57** [comment]
Good work on the script, though. It's just not where I'd have put it :).

**Pull request merged**
