### PR TITLE
Address style issues in kinematics.py

### LINKED ISSUE #39: Kinematics.py should be in the examples folder
The only .py files which should be in the root are ones that need to be there as a necessity of the build system.

### PR DESCRIPTION
**Pull request by rjw57**
This pull-request is further to my comments in #37. I've moved Kinematics.py to the examples directory and fixed some of the style issues flagged by pylint.

It'd be great if @lwc24 could add a descriptive docstring if this PR is merged outlining the purpose of the script, how to run it and how to interpret the output. At the moment kinematics.py is a "mysterious file" lurking in ``examples/``. :).

Fixes #39.

### CODE REVIEW

**Comment by rjw57** [comment]
So, @lwc24, I've added my review of #37 in the form of commits in this PR. I hope they're understandable.

I don't know what this script does, however, and I think that's my main comment.

**Comment by lwc24** [comment]
Improvements sound good to me, will adjust my coding style to match in future! Could add the following as a docstring:

A script to simulate and plot the trajectory of a 3D body through the atmosphere using trapezoidal integration. 

Run via: Kinematics.py

**Comment by rjw57** [comment]
Sounds like a sensible description. Will add once I've checked I've not broken anything :).

**Comment by rjw57** [comment]
Hmm. Travis appeared to have a burp. I've re-started the build. Let's see.

**Comment by jb803** [comment]
For some reason I didn't spot this was here until just as I was about to pull request my code. Whilst procrastarevising I've moved kinematics.py to the examples folder as kinematics_basis.py.

I've then moved the core of the code into a new firefish.kinematics module and created a KinematicBody and KinematicSimulation class and then reimplemented kinematics_basis.py using the new classes as kinematics_example.py

I'll pull request it once it passes Travis but @rjw57 and @lac70 - you might want to take a look in case there's bits that you've fixed here that I've left in. The pull request is #42

**Comment by rjw57** [comment]
Closing since #42 addresses this now.

**Pull request closed without merging**
